### PR TITLE
run shell scripts through wine binary

### PR DESCRIPTION
**Pull request by philipzae**
most shell scripts in /bin/ need to be run as 'wine wineprogram'
https://wiki.winehq.org/List_of_Commands

### CODE REVIEW

**Comment by philipzae** [comment]
Build system is currently broken if https://github.com/probonopd/libhookexecv/pull/18 isnt first applied.

**Comment by probonopd** [comment]
Now that I have merged #18, I'd like to see this build "green" first. But I don't see this button here:



Why?

**Comment by probonopd** [comment]
Maybe you need to close this PR and send a new one so that it builds green. (Or if you are a git wizard on the command line, you may be able to update this PR).

**Comment by philipzae** [comment]
Okay opening new PR. Couldnt find a way to rebase.

**Pull request closed without merging**
