### PR TITLE
run shell scripts through wine binary

### PR DESCRIPTION
**Pull request by philipzae**
most shell scripts in /bin/ need to be run as 'wine wineprogram'
https://wiki.winehq.org/List_of_Commands

### CODE REVIEW

**Comment by philipzae** [comment]
tested notepad, regedit, winecfg, wineconsole, and winemine on build and they worked perfectly.
https://transfer.sh/15HQdi/Wine_Windows_Program_Loader-3.20-x86_64.AppImage

**Comment by probonopd** [comment]
Sine winetricks still segfaults (at least I did not read otherwise), I would like to put this on hold until winetricks is working.

**Comment by philipzae** [comment]
winetricks is a different issue and would need to be resolved differently

**Comment by probonopd** [comment]
Does this PR provide any benefit on its own?

**Comment by philipzae** [comment]
Yes it makes `Wine_Windows_Program_Loader-3.20-x86_64.AppImage notepad` work as presently it gives the below error as it trying to execute `/bin/notepad` directly rather than `/bin/wine notepad`

```
./Wine_Windows_Program_Loader-3.20-x86_64.AppImage notepad
Mounting /tmp/wine_7b28d030f52c7c520501363073eb01abd359d6cd.unionfs
Using /tmp/.mount_Wine_Wm5EZdE/wineprefix mounted to /tmp/wine_7b28d030f52c7c520501363073eb01abd359d6cd.unionfs
/tmp/.mount_Wine_Wm5EZdE/bin/notepad: error while loading shared libraries: /tmp/.mount_Wine_Wm5EZdE/bin/notepad: invalid ELF header
```

**Pull request merged**
