### PR TITLE
bundle winetricks and cabextract

### PR DESCRIPTION
**Pull request by philipzae**

### CODE REVIEW

**Comment by probonopd** [comment]
...almost:

```
me@host:~$ ln -s Downloads/Wine_Windows_Program_Loader-3.5-x86_64.AppImage winetricks
me@host:~$ ./winetricks
Mounting /tmp/wine_c2a2b5bdd1d6ef7886d301d3683f2fcbad86864d.unionfs
Using /tmp/.mount_winetrqktcHo/wineprefix mounted to /tmp/wine_c2a2b5bdd1d6ef7886d301d3683f2fcbad86864d.unionfs
/tmp/.mount_winetrqktcHo/bin/winetricks: error while loading shared libraries: /tmp/.mount_winetrqktcHo/bin/winetricks: invalid ELF header
```

Do you think you can edit around [here](https://github.com/probonopd/libhookexecv/blob/48fe7ddfe3ab73ab08479eaea51a02f5a669ba37/winedeploy.sh#L147-L151) so that bash scripts are not loaded using ld-linux.so a.k.a. `$WINELDLIBRARY`? (Check with `file`, then have an `if`.)

**Comment by philipzae** [comment]
As i dont know bash, i tried and wasnt able to make it work. This is as far as i could get.

```
if [ file --mime-type "$MAIN" == "text/x-shellscript" ] ; then
  "$MAIN" "$@" | cat
elif [ -z "$APPLICATION" ] ; then
  LD_PRELOAD="$HERE/lib/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$@" | cat
else
  LD_PRELOAD="$HERE/lib/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$APPLICATION" | cat
fi
```

**Comment by probonopd** [comment]
Looks approximately right, what happened?

**Comment by mmtrt** [comment]
This should do it though I've only tested `regedit` working fine which is also a shell script, FYI `winetricks` also needs `regedit` to be working and `wine`, `wineserver`, `regsvr32` in path aswell .

You can add more shell script files in if needed.

```
if [ "$MAIN" = "$HERE/bin/regedit" ] || [ "$MAIN" = "$HERE/bin/regsvr32" ] || [ "$MAIN" = "$HERE/bin/winetricks" ]; then
  "$MAIN" "$@" | cat
elif [ -z "$APPLICATION" ] ; then
  LD_PRELOAD="$HERE/bin/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$@" | cat
else
  LD_PRELOAD="$HERE/bin/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$APPLICATION" | cat
fi
```

EDIT: ~~it does almost same but~~ @philipzae ~~is neat one but it depends on file mimetype~~ does not works.

**Comment by probonopd** [comment]
What happens with

```
MIME=$(file --mime-type "$MAIN")
if [ "$MIME" == "text/x-shellscript" ] ; then
```

?

**Comment by mmtrt** [comment]
none works except mine proposed.

**Comment by probonopd** [comment]
What errors are you getting?

**Comment by philipzae** [comment]
This worked as the output is like "./bin/winetricks: text/x-shellscript"

```
MIME=$(file --mime-type "$MAIN")

if [ "$MIME" = "$MAIN: text/x-shellscript" ] ; then
  "$MAIN" "$@" | cat
elif [ -z "$APPLICATION" ] ; then
  LD_PRELOAD="$HERE/bin/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$@" | cat
else
  LD_PRELOAD="$HERE/bin/libhookexecv.so" "$WINELDLIBRARY" "$MAIN" "$APPLICATION" | cat
fi

```

**Comment by probonopd** [comment]
Thank you very much.

**Comment by probonopd** [comment]
Hmm, why is this not working?

```
me@host:~$ Downloads/Wine_Windows_Program_Loader-4.10-x86_64.AppImage winetricksMounting /tmp/wine_c7a07fdbd95a1e58415f9bf37bd0c7ee2b94adf6.unionfs
Using /tmp/.mount_Wine_Wtw4hgJ/wineprefix mounted to /tmp/wine_c7a07fdbd95a1e58415f9bf37bd0c7ee2b94adf6.unionfs
wine: cannot find L"C:\\windows\\system32\\winetricks.exe"
```

**Comment by philipzae** [comment]
I tested the build version [ https://transfer.sh/CRAZo/Wine_Windows_Program_Loader-3.20-x86_64.AppImage ] and it worked, though it results in a segfault.

```
Segmentation fault (core dumped)
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 20
drwxrwxr-x  5 jay jay 4096 Jul  2 04:29 .
drwxrwxr-x  4 jay jay 4096 Jul  2 04:29 ..
drwxrwxr-x  6 jay jay 4096 Jul  2 04:29 Program Files
drwxrwxr-x  3 jay jay 4096 Jul  2 04:29 ProgramData
lrwxrwxrwx  1 jay jay    5 Jul  1 02:07 users -> /home
drwxrwxr-x 13 jay jay 4096 Jul  2 04:29 windows

Registry info:
/home/jay/Downloads/wine/probono-AppImage/wineprefix/system.reg:#arch=win32
/home/jay/Downloads/wine/probono-AppImage/wineprefix/user.reg:#arch=win32
/home/jay/Downloads/wine/probono-AppImage/wineprefix/userdef.reg:#arch=win32
------------------------------------------------------
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "" 
------------------------------------------------------
```

**Comment by mmtrt** [comment]
I'm also getting `seg fault core dump` with my changes as well in `kde neon` system, weird thing is that same thing is working fine in `Manjaro` on my other system. Could this be related to appimage tools causing such behavior.

Also tested appimage linked by @philipzae it is showing error `wineserver is not found` in `Manjaro`

EDIT: after symlinking appimage as `wine` `wineserver` to bin then launching `appimage` with `winetricks` is working fine now and also symlinking `appimage` as `winetricks` and calling only `winetricks` works as well on `Manjaro` system

EDIT2: Looks like this will only work if appimage is linked as `wine` `wineserver` etc. I think this is bad what happens when the user have `wine` already in their systems?

**Comment by philipzae** [comment]
> wine: cannot find L"C:\\windows\\system32\\winetricks.exe"

I got this when winetricks wasnt found in /bin/

**Comment by philipzae** [comment]
If you run `winetricks --version`, it will work correctly, so the winetricks file needs modification in order for it to run effectively in the appimage. Some of the lines that i noticed were having issues are

https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L4802
https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L3112

**Comment by probonopd** [comment]
What is "the AppImage" doing that makes those lines fail?

**Comment by philipzae** [comment]
winetricks is failing most likely because it doesnt know about LD_PRELOAD and WINELDLIBRARY and /bin/wine in the appimage cant run without it.

**Comment by mmtrt** [comment]
After taking bash at winetricks issue so now I've fixed winetricks issue, winetricks need this in order to function.

```
export WINEPATH="$HERE"
export WINE="${WINEPATH}/bin/wine"
```

EDIT: My `archlinux` version `appimage` still seg faults in `kde neon` so I've reverted changes and decided to not ship `winetricks`.

**Comment by philipzae** [comment]
> ```
> export WINEPATH="$HERE"
> export WINE="${WINEPATH}/bin/wine"
> ```

I had thought along those same lines at one point, but found that winetricks did correctly find the WINE path.

**Pull request merged**
