### PR TITLE
dont symlink c:\users to /home

### PR DESCRIPTION
**Pull request by philipzae**
instead create a user folder in c:\users and symlink the user's desktop, documents, music and video folders

### CODE REVIEW

**Comment by probonopd** [comment]
Why?

**Comment by probonopd** [comment]
I see, it's described in https://github.com/probonopd/libhookexecv/issues/15. Makes sense to me.

**Comment by philipzae** [comment]
I made a mistake on this as the code should have been in the AppRun. Should we revert and i send in a new PR?

**Comment by probonopd** [comment]
Yes, just close the old PR and send a new PR please.

**Comment by philipzae** [comment]
Done - https://github.com/probonopd/libhookexecv/pull/18

**Pull request merged**
